# Generated by Django 3.1.3 on 2020-11-12 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simplechat', '0002_auto_20201112_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
